db:
  image: mongo
  ports:
    - "27017:27017"
web:
  build: .
#  volumes:
#    - .:/code
  command: bash -c "yarn install && yarn run start"
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PORT: 3000